// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/laundry/internal/core/domain"
	mock "github.com/stretchr/testify/mock"

	transformer "github.com/laundry/internal/core/transformer"
)

// AuthRepository is an autogenerated mock type for the AuthRepository type
type AuthRepository struct {
	mock.Mock
}

// GenerateJWT provides a mock function with given fields: ctx, user
func (_m *AuthRepository) GenerateJWT(ctx context.Context, user domain.User) (*transformer.GenerateJWTTransformer, error) {
	ret := _m.Called(ctx, user)

	var r0 *transformer.GenerateJWTTransformer
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) *transformer.GenerateJWTTransformer); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transformer.GenerateJWTTransformer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GeneratePassword provides a mock function with given fields: ctx, password
func (_m *AuthRepository) GeneratePassword(ctx context.Context, password string) (string, error) {
	ret := _m.Called(ctx, password)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
