// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/laundry/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// AuthRepository is an autogenerated mock type for the AuthRepository type
type AuthRepository struct {
	mock.Mock
}

// DeleteRefreshToken provides a mock function with given fields: ctx, jti
func (_m *AuthRepository) DeleteRefreshToken(ctx context.Context, jti string) error {
	ret := _m.Called(ctx, jti)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, jti)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenerateAccessToken provides a mock function with given fields: ctx, user
func (_m *AuthRepository) GenerateAccessToken(ctx context.Context, user domain.User) (*domain.GenerateJWTResponse, error) {
	ret := _m.Called(ctx, user)

	var r0 *domain.GenerateJWTResponse
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) *domain.GenerateJWTResponse); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GenerateJWTResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateJWT provides a mock function with given fields: ctx, user
func (_m *AuthRepository) GenerateJWT(ctx context.Context, user domain.User) (*domain.GenerateJWTResponse, error) {
	ret := _m.Called(ctx, user)

	var r0 *domain.GenerateJWTResponse
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) *domain.GenerateJWTResponse); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GenerateJWTResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GeneratePassword provides a mock function with given fields: ctx, password
func (_m *AuthRepository) GeneratePassword(ctx context.Context, password string) (string, error) {
	ret := _m.Called(ctx, password)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateSession provides a mock function with given fields: ctx, uuid, expired
func (_m *AuthRepository) GenerateSession(ctx context.Context, uuid string, expired uint) (*domain.GenerateSessionRespose, error) {
	ret := _m.Called(ctx, uuid, expired)

	var r0 *domain.GenerateSessionRespose
	if rf, ok := ret.Get(0).(func(context.Context, string, uint) *domain.GenerateSessionRespose); ok {
		r0 = rf(ctx, uuid, expired)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GenerateSessionRespose)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, uint) error); ok {
		r1 = rf(ctx, uuid, expired)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateRefreshToken provides a mock function with given fields: ctx, refreshToken
func (_m *AuthRepository) ValidateRefreshToken(ctx context.Context, refreshToken string) (*domain.RefreshTokenDataClaim, error) {
	ret := _m.Called(ctx, refreshToken)

	var r0 *domain.RefreshTokenDataClaim
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.RefreshTokenDataClaim); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefreshTokenDataClaim)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateSession provides a mock function with given fields: ctx, sessionToken
func (_m *AuthRepository) ValidateSession(ctx context.Context, sessionToken string) (*domain.ValidateSession, error) {
	ret := _m.Called(ctx, sessionToken)

	var r0 *domain.ValidateSession
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.ValidateSession); ok {
		r0 = rf(ctx, sessionToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ValidateSession)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
