// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/laundry/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// LoginService is an autogenerated mock type for the LoginService type
type LoginService struct {
	mock.Mock
}

// DoLogin provides a mock function with given fields: ctx, request
func (_m *LoginService) DoLogin(ctx context.Context, request domain.DoLoginRequest) (*domain.DoLoginResponse, error) {
	ret := _m.Called(ctx, request)

	var r0 *domain.DoLoginResponse
	if rf, ok := ret.Get(0).(func(context.Context, domain.DoLoginRequest) *domain.DoLoginResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DoLoginResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.DoLoginRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DoLogout provides a mock function with given fields: ctx, request
func (_m *LoginService) DoLogout(ctx context.Context, request domain.DoLogoutRequest) (*string, error) {
	ret := _m.Called(ctx, request)

	var r0 *string
	if rf, ok := ret.Get(0).(func(context.Context, domain.DoLogoutRequest) *string); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.DoLogoutRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DoRefreshToken provides a mock function with given fields: ctx, request
func (_m *LoginService) DoRefreshToken(ctx context.Context, request domain.DoRefreshTokenRequest) (*domain.DoRefreshTokenResponse, error) {
	ret := _m.Called(ctx, request)

	var r0 *domain.DoRefreshTokenResponse
	if rf, ok := ret.Get(0).(func(context.Context, domain.DoRefreshTokenRequest) *domain.DoRefreshTokenResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DoRefreshTokenResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.DoRefreshTokenRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
