// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/laundry/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// OtpRepository is an autogenerated mock type for the OtpRepository type
type OtpRepository struct {
	mock.Mock
}

// DeleteOTP provides a mock function with given fields: ctx, uuid
func (_m *OtpRepository) DeleteOTP(ctx context.Context, uuid string) error {
	ret := _m.Called(ctx, uuid)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenerateOTP provides a mock function with given fields: ctx, uuid, expired
func (_m *OtpRepository) GenerateOTP(ctx context.Context, uuid string, expired uint) (*domain.DefaultOTP, error) {
	ret := _m.Called(ctx, uuid, expired)

	var r0 *domain.DefaultOTP
	if rf, ok := ret.Get(0).(func(context.Context, string, uint) *domain.DefaultOTP); ok {
		r0 = rf(ctx, uuid, expired)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DefaultOTP)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, uint) error); ok {
		r1 = rf(ctx, uuid, expired)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOTPByUUID provides a mock function with given fields: ctx, uuid
func (_m *OtpRepository) GetOTPByUUID(ctx context.Context, uuid string) (*domain.DefaultOTP, error) {
	ret := _m.Called(ctx, uuid)

	var r0 *domain.DefaultOTP
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.DefaultOTP); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DefaultOTP)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
