// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/laundry/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// RegisterService is an autogenerated mock type for the RegisterService type
type RegisterService struct {
	mock.Mock
}

// BeforeRegisterWithEmail provides a mock function with given fields: ctx, request
func (_m *RegisterService) BeforeRegisterWithEmail(ctx context.Context, request domain.BeforeRegisterWithEmail) (*domain.BeforeRegisterResponse, error) {
	ret := _m.Called(ctx, request)

	var r0 *domain.BeforeRegisterResponse
	if rf, ok := ret.Get(0).(func(context.Context, domain.BeforeRegisterWithEmail) *domain.BeforeRegisterResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BeforeRegisterResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.BeforeRegisterWithEmail) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BeforeRegisterWithPhone provides a mock function with given fields: ctx, request
func (_m *RegisterService) BeforeRegisterWithPhone(ctx context.Context, request domain.BeforeRegisterWithPhone) (*domain.BeforeRegisterResponse, error) {
	ret := _m.Called(ctx, request)

	var r0 *domain.BeforeRegisterResponse
	if rf, ok := ret.Get(0).(func(context.Context, domain.BeforeRegisterWithPhone) *domain.BeforeRegisterResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BeforeRegisterResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.BeforeRegisterWithPhone) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfirmationRegister provides a mock function with given fields: ctx, request
func (_m *RegisterService) ConfirmationRegister(ctx context.Context, request domain.ConfirmationRegisterRequest) (*domain.GenerateSessionRespose, error) {
	ret := _m.Called(ctx, request)

	var r0 *domain.GenerateSessionRespose
	if rf, ok := ret.Get(0).(func(context.Context, domain.ConfirmationRegisterRequest) *domain.GenerateSessionRespose); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GenerateSessionRespose)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.ConfirmationRegisterRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DoRegister provides a mock function with given fields: ctx, request
func (_m *RegisterService) DoRegister(ctx context.Context, request domain.DoRegisterRequest) (*domain.DoRegisterResponse, error) {
	ret := _m.Called(ctx, request)

	var r0 *domain.DoRegisterResponse
	if rf, ok := ret.Get(0).(func(context.Context, domain.DoRegisterRequest) *domain.DoRegisterResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DoRegisterResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.DoRegisterRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResendCode provides a mock function with given fields: ctx, request
func (_m *RegisterService) ResendCode(ctx context.Context, request domain.ResendCodeRequest) (*domain.DefaultOTP, error) {
	ret := _m.Called(ctx, request)

	var r0 *domain.DefaultOTP
	if rf, ok := ret.Get(0).(func(context.Context, domain.ResendCodeRequest) *domain.DefaultOTP); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DefaultOTP)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.ResendCodeRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
